CREATE TABLE IF NOT EXISTS users (
  userId SERIAL PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(40) NOT NULL,
  password VARCHAR(20) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS folders (
  folderId SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  color VARCHAR(20) NOT NULL,
  userId INT NOT NULL,
  FOREIGN KEY (userId) REFERENCES users(userId)
);

CREATE TABLE IF NOT EXISTS notes (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  htmlNotes TEXT,
  userId INT NOT NULL,
  FOREIGN KEY (userId) REFERENCES users(userId)
);
